name: build_and_push_to_manifest
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  
jobs:

  test_and_build:
    name: build and push docker image
    if: contains(github.ref, 'refs/heads/')
    runs-on: [self-hosted, linux, k8s]
    services:
      mongodb:
        image: mongo:4.4-focal
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Run Unit Tests
        run: go test ./... -race -covermode=atomic -coverprofile=coverage.out

      - name: Build main
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o sfeir_bin